name: CI

on:
  push: {}
  schedule:
  - cron:  '0 6 * * 0' # weekly, on sundays

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: rwjblue/setup-volta@v1
      with:
        node-version: '8'
        yarn-version: '1'
    - name: install dependencies
      run: yarn
    - name: lint
      run: yarn lint
    - name: test
      run: yarn test
